# Generated by Django 5.2.8 on 2025-11-11 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('invite_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagStyle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_detail', models.CharField(max_length=20)),
                ('tag_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='올바른 HEX 색상 코드를 입력하세요 (예: #AABBCC)', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_styles', to='portfolios.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'tag_detail'), name='unique_tag_detail_per_project'), models.UniqueConstraint(fields=('project', 'tag_color'), name='unique_tag_color_per_project')],
            },
        ),
    ]
