# Generated by Django 5.1.7 on 2025-11-13 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagstyle',
            name='tag_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='올바른 HEX 색상 코드를 입력하세요 (예: #AABBCC)', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
