# Generated by Django 5.2.8 on 2025-11-18 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'project', 'reason', 'created_at'], name='portfolios__user_id_6b397f_idx'),
        ),
    ]
