# Generated by Django 5.2.8 on 2025-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='date',
            field=models.DateField(default='2025-11-13'),
            preserve_default=False,
        ),
    ]
