# Generated by Django 5.2.8 on 2025-11-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memos', '0001_initial'),
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_contents', models.CharField(max_length=20)),
                ('offset_start', models.PositiveIntegerField(default=0)),
                ('offset_end', models.PositiveIntegerField(default=0)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='memos.memo')),
                ('tag_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='portfolios.tagstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
