# Generated by Django 5.2.8 on 2025-11-14 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagStyle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_detail', models.CharField(max_length=20, unique=True)),
                ('tag_color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='올바른 HEX 색상 코드를 입력하세요 (예: #AABBCC)', regex='^#[0-9a-fA-F]{6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_contents', models.CharField(max_length=20)),
                ('offset_start', models.PositiveIntegerField(default=0)),
                ('offset_end', models.PositiveIntegerField(default=0)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='memos.memo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to=settings.AUTH_USER_MODEL)),
                ('tag_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='taggings.tagstyle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
