# Generated by Django 5.2.8 on 2025-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='tag_contents',
            field=models.CharField(max_length=500),
        ),
    ]
